version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lesson
    restart: always
    networks:
      - lesson
networks:
  lesson: